version: 1
disable_existing_loggers: true # set to False to enable other existing loggers
formatters:
  formatter:
    format: "{{ hostname }} - %(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: formatter
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    encoding: "utf-8"
    formatter: formatter
    when: midnight
    backupCount: 30
    interval: 1
    filename: "{{ file_path }}"
loggers:
  clogger:
    level: DEBUG
    handlers: [console]
    propagate: true
  flogger:
    level: INFO
    handlers: [file]
    propagate: true
root:
  level: DEBUG
  handlers: [console]
  propagate: true